---
- hosts: localhost
  become: yes
  become_user: gova  # Switch to user gova
  become_method: sudo
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: dev1
        comment: "Development team"
        state: present
